OBJ=andrsource/out/soong/.intermediates/system/bt
andrsource/prebuilts/clang/host/linux-x86/clang-4691093/bin/llvm-link \
$OBJ/main/libbluetooth/android_arm64_armv8-2a_cortex-a75_core_shared/obj/system/bt/main/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/ag/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/ar/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/av/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/dm/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/hd/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/hh/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/hl/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/jv/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/mce/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/pan/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/sdp/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/sys/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/gatt/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/hf_client/*.o \
$OBJ/bta/libbt-bta/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/bta/hearing_aid/*.o \
$OBJ/btif/libbtif/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/btif/src/*.o \
$OBJ/btif/libbtif/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/btif/co/*.o \
$OBJ/btif/libbtif/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/btif/avrcp/*.o \
$OBJ/hci/libbt-hci/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/hci/src/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/gatt/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/sdp/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/pan/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/btm/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/btu/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/gap/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/hid/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/smp/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/a2dp/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/avct/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/avdt/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/avrc/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/bnep/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/hcic/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/mcap/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/srvc/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/l2cap/*.o \
$OBJ/stack/libbt-stack/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/stack/rfcomm/*.o \
$OBJ/utils/libbt-utils/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/utils/src/*.o \
$OBJ/profile/avrcp/avrcp-target-service/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/profile/avrcp/*.o \
$OBJ/device/libbtdevice/android_arm64_armv8-2a_cortex-a75_core_static/obj/system/bt/device/src/*.o \
-o $1
